env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: latest
  sourceType: module
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
plugins:
  - react
overrides:
  - extends:
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
      - plugin:react/recommended
      - prettier
    files:
      - '**/*.ts?(x)'
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaFeatures:
        jsx: true
      ecmaVersion: latest
      sourceType: module
    plugins:
      - '@typescript-eslint'
