env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
plugins:
  - '@typescript-eslint'
  - react
rules: {}
