ci:
  collect:
    numberOfRuns: 5
    # staticDistDir: './build'
    startServerCommand: pnpm run preview
    url:
      [
        'http://localhost:3000/spark-react-crud',
        # 'http://localhost/posts/1',
        # 'http://localhost/posts/1/edit',
        # 'http://localhost/posts/new',
      ]
    isSinglePageApplication: true
  assert:
    assertions:
      'categories:performance': ['error', { 'minScore': 0.83 }]
      'categories:accessibility': ['error', { 'minScore': 0.97 }]
      'categories:best-practices': ['error', { 'minScore': 0.92 }]
      'categories:pwa': ['off']
      'categories:seo': ['error', { 'minScore': 0.83 }]
  upload:
    target: 'temporary-public-storage'
